<?php
/**
 * Hero section.
 *
 * @package ProjectTheme
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'get_sub_field' ) ) {
	return;
}

$section_id           = project_theme_section_id( (string) get_sub_field( 'section_id' ), 'top' );
$eyebrow              = (string) get_sub_field( 'eyebrow' );
$title                 = (string) get_sub_field( 'title' );
$lead                  = (string) get_sub_field( 'lead' );
$primary_link          = project_theme_link( get_sub_field( 'primary_link' ) );
$secondary_button_text = (string) get_sub_field( 'secondary_button_text' );
$secondary_interest    = (string) get_sub_field( 'secondary_interest' );
$secondary_context     = (string) get_sub_field( 'secondary_context' );
$developer_prefix      = (string) get_sub_field( 'developer_prefix' );
$developer_name        = (string) get_sub_field( 'developer_name' );
$image_id              = (int) get_sub_field( 'image' );
$image_alt             = (string) get_sub_field( 'image_alt' );
$image_caption         = (string) get_sub_field( 'image_caption' );
$badge_value           = (string) get_sub_field( 'badge_value' );
$badge_label           = (string) get_sub_field( 'badge_label' );
$metrics               = get_sub_field( 'metrics' );
$metrics               = is_array( $metrics ) ? $metrics : array();
$image_html            = project_theme_image_html( $image_id, $image_alt, array() );
$has_figure            = '' !== $image_html || '' !== $image_caption || '' !== $badge_value || '' !== $badge_label;
?>
<section class="hero" id="<?php echo esc_attr( $section_id ); ?>">
	<div class="container hero-panel">
		<div class="hero-copy reveal">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="eyebrow"><span></span><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>
			<?php if ( '' !== $title ) : ?>
				<h1><?php echo esc_html( $title ); ?></h1>
			<?php endif; ?>
			<?php if ( '' !== $lead ) : ?>
				<p class="hero-lead"><?php echo esc_html( $lead ); ?></p>
			<?php endif; ?>
			<?php if ( ( '' !== $primary_link['url'] && '' !== $primary_link['title'] ) || '' !== $secondary_button_text ) : ?>
				<div class="hero-actions">
					<?php if ( '' !== $primary_link['url'] && '' !== $primary_link['title'] ) : ?>
						<a class="button button--green" href="<?php echo esc_url( $primary_link['url'] ); ?>"<?php if ( '' !== $primary_link['target'] ) : ?> target="<?php echo esc_attr( $primary_link['target'] ); ?>"<?php endif; ?><?php if ( '_blank' === $primary_link['target'] ) : ?> rel="noopener noreferrer"<?php endif; ?>><?php echo esc_html( $primary_link['title'] ); ?></a>
					<?php endif; ?>
					<?php if ( '' !== $secondary_button_text ) : ?>
						<button class="button button--light" type="button" data-open-lead data-interest="<?php echo esc_attr( $secondary_interest ); ?>" data-context="<?php echo esc_attr( $secondary_context ); ?>"><?php echo esc_html( $secondary_button_text ); ?></button>
					<?php endif; ?>
				</div>
			<?php endif; ?>
			<?php if ( '' !== $developer_prefix || '' !== $developer_name ) : ?>
				<p class="developer"><?php echo esc_html( $developer_prefix ); ?><?php if ( '' !== $developer_prefix && '' !== $developer_name ) : ?> <?php endif; ?><?php if ( '' !== $developer_name ) : ?><strong><?php echo esc_html( $developer_name ); ?></strong><?php endif; ?></p>
			<?php endif; ?>
		</div>

		<?php if ( $has_figure ) : ?>
			<figure class="hero-image reveal reveal--delay">
				<?php echo $image_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by project_theme_image_html(). ?>
				<?php if ( '' !== $image_caption ) : ?>
					<figcaption><?php echo esc_html( $image_caption ); ?></figcaption>
				<?php endif; ?>
				<?php if ( '' !== $badge_value || '' !== $badge_label ) : ?>
					<span class="hero-badge"><?php if ( '' !== $badge_value ) : ?><b><?php echo esc_html( $badge_value ); ?></b><?php endif; ?><?php if ( '' !== $badge_value && '' !== $badge_label ) : ?> <?php endif; ?><?php echo esc_html( $badge_label ); ?></span>
				<?php endif; ?>
			</figure>
		<?php endif; ?>

		<?php if ( $metrics ) : ?>
			<div class="metric-grid reveal">
				<?php foreach ( $metrics as $metric ) : ?>
					<?php
					if ( ! is_array( $metric ) ) {
						continue;
					}
					$metric_value = isset( $metric['value'] ) ? (string) $metric['value'] : '';
					$metric_label = isset( $metric['label'] ) ? (string) $metric['label'] : '';
					?>
					<article><strong><?php echo esc_html( $metric_value ); ?></strong><span><?php echo esc_html( $metric_label ); ?></span></article>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>
	</div>
</section>
